# =============================================
#  Cloudflare Pages Configuration
#  منصة أثر التعليمية
# =============================================

name = "athr-platform"
compatibility_date = "2025-10-01"

# تحديد مجلد الملفات الثابتة
[assets]
directory = "."

# استبعاد الملفات غير الضرورية
[assets.exclude]
patterns = ["node_modules", ".git", "*.log", "package*.json", "wrangler.toml"]
